#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : R-prodlim
Version  : 2024.06.25
Release  : 55
URL      : https://cran.r-project.org/src/contrib/prodlim_2024.06.25.tar.gz
Source0  : https://cran.r-project.org/src/contrib/prodlim_2024.06.25.tar.gz
Summary  : Product-Limit Estimation for Censored Event History Analysis
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-prodlim-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-data.table
Requires: R-diagram
Requires: R-lava
BuildRequires : R-Rcpp
BuildRequires : R-data.table
BuildRequires : R-diagram
BuildRequires : R-lava
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
for censored event history (survival) analysis. Kaplan-Meier and
    Aalen-Johansen method.

%package lib
Summary: lib components for the R-prodlim package.
Group: Libraries

%description lib
lib components for the R-prodlim package.


%prep
%setup -q -n prodlim
pushd ..
cp -a prodlim buildavx2
popd
pushd ..
cp -a prodlim buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719252810

%install
export SOURCE_DATE_EPOCH=1719252810
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/prodlim/DESCRIPTION
/usr/lib64/R/library/prodlim/INDEX
/usr/lib64/R/library/prodlim/Meta/Rd.rds
/usr/lib64/R/library/prodlim/Meta/features.rds
/usr/lib64/R/library/prodlim/Meta/hsearch.rds
/usr/lib64/R/library/prodlim/Meta/links.rds
/usr/lib64/R/library/prodlim/Meta/nsInfo.rds
/usr/lib64/R/library/prodlim/Meta/package.rds
/usr/lib64/R/library/prodlim/NAMESPACE
/usr/lib64/R/library/prodlim/R/prodlim
/usr/lib64/R/library/prodlim/R/prodlim.rdb
/usr/lib64/R/library/prodlim/R/prodlim.rdx
/usr/lib64/R/library/prodlim/help/AnIndex
/usr/lib64/R/library/prodlim/help/aliases.rds
/usr/lib64/R/library/prodlim/help/paths.rds
/usr/lib64/R/library/prodlim/help/prodlim.rdb
/usr/lib64/R/library/prodlim/help/prodlim.rdx
/usr/lib64/R/library/prodlim/html/00Index.html
/usr/lib64/R/library/prodlim/html/R.css
/usr/lib64/R/library/prodlim/tests/testthat/test-prodlim.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/prodlim/libs/prodlim.so
/V4/usr/lib64/R/library/prodlim/libs/prodlim.so
/usr/lib64/R/library/prodlim/libs/prodlim.so
